# Generated by Django 2.2.3 on 2019-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCrm_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='empty', max_length=100, null=True)),
                ('client_contact', models.CharField(default='empty', max_length=100, null=True)),
                ('client_goal', models.CharField(default='empty', max_length=300, null=True)),
                ('client_comment', models.CharField(default='empty', max_length=250, null=True)),
                ('client_income_date', models.CharField(default='empty', max_length=14, null=True)),
                ('client_last_date', models.CharField(default='empty', max_length=14, null=True)),
                ('client_trashed_date', models.CharField(default='empty', max_length=14, null=True)),
                ('client_status', models.CharField(default='emtpy', max_length=20, null=True)),
                ('isvisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCrm_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
