# Generated by Django 2.2.3 on 2019-08-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcrm_client',
            name='client_last_event',
            field=models.CharField(default='empty', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gcrm_client',
            name='client_next_date',
            field=models.CharField(default='empty', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='gcrm_client',
            name='client_next_event',
            field=models.CharField(default='empty', max_length=30, null=True),
        ),
    ]
