# Generated by Django 2.2.3 on 2019-09-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_crm', '0002_auto_20190827_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCrm_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_file', models.FileField(upload_to='clients/%Y/%m_%d')),
                ('file_type', models.CharField(default='empty', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_file', to='global_crm.GCrm_Client')),
            ],
        ),
    ]
