# Generated by Django 2.2 on 2019-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0010_auto_20190226_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='veh_type',
            field=models.CharField(choices=[('salon', 'салон'), ('dealler', 'диллер')], default=('salon', 'салон'), max_length=20),
        ),
    ]
