# Generated by Django 2.2 on 2019-07-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0011_auto_20190411_0730'),
        ('electrocars', '0015_auto_20190703_2214'),
    ]

    operations = [
    ]
