# Generated by Django 2.2 on 2019-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_crm', '0003_auto_20190701_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_clients',
            name='veh_body',
            field=models.CharField(default='empty', max_length=250, null=True),
        ),
    ]
