# Generated by Django 2.2 on 2019-07-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh_crm', '0004_auto_20190703_2213'),
        ('gh_crm', '0004_auto_20190701_1530'),
    ]

    operations = [
    ]
